spring.datasource.url: jdbc:postgresql://localhost:5432/restCrudExample
spring.datasource.username: dbuser
spring.datasource.password: dbpass
spring.jpa.hibernate.ddl-auto: create-drop

kafka.bootstrap: localhost:9092,localhost:9093,localhost:9094