version: '2'

services:
    zookeeper:
        build:
            context: .
            args:
                kafkaPath: kafka_2.11-2.0.0
        command: /kafka/bin/zookeeper-server-start.sh /kafka/config/zookeeper.properties
        ports:
        - 2181:2181
        depends_on:
          - rabbitmq

    kafka1:
        build:
            context: .
            args:
                brokerId: 1
                kafkaPath: kafka_2.11-2.0.0
        command: /kafka/bin/kafka-server-start.sh /kafka/config/server.properties
        depends_on:
        - zookeeper
        ports:
        - 9092:9092

    kafka2:
        build:
            context: .
            args:
                brokerId: 2
                kafkaPath: kafka_2.11-2.0.0

        command: /kafka/bin/kafka-server-start.sh /kafka/config/server.properties
        depends_on:
        - zookeeper
        ports:
        - 9093:9092
    kafka3:
        build:
            context: .
            args:
                brokerId: 3
                kafkaPath: kafka_2.11-2.0.0
        command: /kafka/bin/kafka-server-start.sh /kafka/config/server.properties
        depends_on:
        - zookeeper
        ports:
        - 9094:9092

    rabbitmq:
      image: rabbitmq:3-management
      logging:
          driver: none
      ports:
        - "15672:15672"
        - "5672:5672"
