version: '2'

services:
  database:
    image: postgres:9.6-alpine
    environment:
    - POSTGRES_USER=dbuser
    - POSTGRES_PASSWORD=dbpass
    - POSTGRES_DB=restCrudExample
    ports:
    - "5432:5432"
